### ISSUE TITLE
Usage from Spring Boot

### ISSUE THREAD

**Issue by Allsimon** [paketo-buildpacks/google-stackdriver#1]
Hello,

This is not directly an issue (perhaps with the documentation (?)).

I'm wondering how to use this from a [Spring Boot](https://spring.io/blog/2020/01/27/creating-docker-images-with-spring-boot-2-3-0-m1) project ? 

The README states: 
>This buildpack will participate if any of the following conditions are met
    A binding exists with type of StackdriverDebugger
    A binding exists with type of StackdriverProfiler

but I can't find any clarifications on Google

**Comment by nebhale** [comment]
Yeah, this is a hole in our documentation on how precisely to use Bindings.  Rest assured that in the next week we're planning on updated the https://paketo.io/ documentation to describe this in much more detail, but I'll give you a rundown here so that you don't have to wait any longer.

Nearly all of the Paketo buildpack integrations with other services make use of something called a Service Binding which is described by the [Kubernetes Service Binding Specification](https://k8s-service-bindings.github.io/spec/#application-projection).  While Kubernetes isn't required for bindings, the project does want to align with Kubernetes where possible and therefore adopts this.

A binding from the buildpack's perspective looks like:

1.  A directory structure that looks a lot like a Kubernetes volume-mounted secret
2. A `$SERVICE_BINDING_ROOT` environment variable pointing to the top of a collection of bindings

So when the docs say "A binding exists with type of `StackdriverDebugger`", effectively what it's looking for is a directory structure like the following:

```
/platform/bindings/my-service
├── ApplicationCredentials
└── type
```

where the contents of `type` are `StackdriverDebugger` and `ApplicationCredentials` contains the JSON payload traditionally used for accessing Google services.  In addition, there should be a `$SERVICE_BINDING_ROOT` with `/platform/bindings` defined.

Concretely, using `pack`, you'll want to do the following:

```
$ mkdir my-service
$ echo "StackdriverDebugger" > my-service/type
$ echo "<json>" > my-service/ApplicationCredentials

$ pack build my-image \
    --env SERVICE_BINDING_ROOT=/platform/bindings \
    --volume $(pwd)/my-service:/platform/bindings/my-service \
    --path my-application
$ docker run -t \
    --env SERVICE_BINDING_ROOT=/platform/bindings \
    --volume $(pwd)/my-service:/platform/bindings/my-service \
    my-image
```

**Comment by Allsimon** [comment]
That makes sense, thanks for the explanation.

I'm not sure how to inject the `/platform/bindings/my-service` directory when building with [https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/html/#build-image](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/html/#build-image). Is `pack` mandatory ?

**Comment by nebhale** [comment]
@Allsimon that's a good question for the Boot team.  @scottfrederick is there's bindings/volume mount support in the Boot plugin?

If there's not then yes `pack` would be the next stop for you.  Alternately, the [`kpack` project](https://github.com/pivotal/kpack) might be an option if you're looking for a builds-as-a-service for multiple projects.

**Comment by scottfrederick** [comment]
> is there's bindings/volume mount support in the Boot plugin?

Not currently. I created an issue to consider adding this to the plugins: https://github.com/spring-projects/spring-boot/issues/23518
